name: Daily Sentiment Log

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  sentiment_log:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run logger
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: |
        export BEARER_TOKEN=$BEARER_TOKEN
        python log_sentiment.py
